apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  labels:
    app: python-app
spec:
  selector:
    app: python-app
  ports:
  - protocol: TCP
    port: 80                   # Expose externally at port 80
    targetPort: 8080
  type: NodePort               # Expose the service on a node
