name: python application ci-cd

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Authenticate to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build the Docker image
        run: docker build . --file app.dockerfile --tag ghcr.io/${{ github.repository_owner }}/github_actions:${{ github.sha }}

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository_owner }}/github_actions:${{ github.sha }}

      - name: Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/github_actions:${{ github.sha }}
          severity: HIGH,CRITICAL         # Report only HIGH and CRITICAL vulnerabilities
          format: table                   # Output vulnerabilities in table format
          ignore-unfixed: true            # Ignore unfixed vulnerabilities (optional)


      - name: Performance Test
        uses: ./.github/actions/performance-test
        with:
          endpoint: http://localhost:8080

  deploy:
    name: Deploy to Staging
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Set up kubeconfig for Kubernetes
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Set up kubeconfig for Kind Cluster
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Test kubernetees Connections
        run: kubectl get nodes

      # Step 2: Create Kubernetes Secret for GHCR Credentials
      - name: Create Secret for GHCR in Kubernetes
        run: |
          kubectl create secret docker-registry ghcr-secret \
            --docker-server=ghcr.io \
            --docker-username=$GITHUB_ACTOR \
            --docker-password=${{ secrets.GITHUB_TOKEN }} \
            --docker-email=nkummuru@example.com --dry-run=client -o yaml | kubectl apply -f -

      # Step 3: Apply Deployment Manifest to Kubernetes
      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      # Step 4: Verify Deployment
      - name: Verify Deployment Status
        run: kubectl rollout status deployment/python-app
