name: python application ci-cd

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Authenticate to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build the Docker image
        run: docker build . --file app.dockerfile --tag ghcr.io/${{ github.repository_owner }}/github_actions:${{ github.sha }}

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository_owner }}/github_actions:${{ github.sha }}

      - name: Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/github_actions:${{ github.sha }}
          severity: HIGH,CRITICAL         # Report only HIGH and CRITICAL vulnerabilities
          format: table                   # Output vulnerabilities in table format
          ignore-unfixed: true            # Ignore unfixed vulnerabilities (optional)


      - name: Performance Test
        uses: ./.github/actions/performance-test
        with:
          endpoint: http://localhost:8080

      # Step 5: Update Kubernetes Deployment YAML for GitOps
      - name: Replace Image Tag in Deployment YAML
        run: |
          sed -i "s|ghcr.io/\${{ github.repository_owner }}/github_actions:\${{ github.sha }}|ghcr.io/${{ github.repository_owner }}/github_actions:${{ github.sha }}|g" k8s/deployment.yaml

      # Step 6: Push Updated Manifest to GitOps Repository
      - name: Commit and Push Kubernetes Manifests
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update deployment image to ghcr.io/${{ github.repository_owner }}/github_actions:${{ github.sha }}"
          git push origin main
